# Generated by Django 3.2.4 on 2021-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('keywords', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('og_description', models.TextField(null=True)),
            ],
        ),
    ]
